name: aidana
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.3

  cupertino_icons: ^1.0.5
  fluttertoast: ^8.2.2
  flutter_svg: ^2.0.7
  flutter_easyloading: ^3.0.5

  dio: ^5.3.2

  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0

  get_it: ^7.6.0
  injectable: ^2.3.0
  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.3.1
  injectable_generator: ^2.4.0
  build_runner: ^2.4.6
  freezed: ^2.4.2

  lint: ^2.1.2
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
